server:
  servlet:
    context-path: /springboot
  port: 8081
#application.yml 可放在更目录以及 config目录下
#     一个/config当前目录的子目录
#     当前目录
#     一个classpath /config包
#     类路径根
#     列表按优先级排序（在列表中较高位置定义的属性将覆盖在较低位置中定义的属性）
#请求详情日志
spring:
  http:
    log-request-details:  false
  devtools:
    restart:
      additional-exclude: "index.html" #添加额外的文件
      log-condition-evaluation-delta: false #禁用重启的日志记录
      exclude:  com.xks
      enabled:  false #关闭重启：
    #  profiles:
    #    active: dev
    #include:   #同事加载dev 用于分开配置文件
  datasource:
    url:  jdbc:mysql://127.0.0.1/base_db
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver