
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      datasource:
        master:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.1.103:3306/wh_smz_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
            username: root
            password: zxhz@#_123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            #Oracle需要打开注释
              #validation-query: SELECT 1 FROM DUAL
        pay:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.1.103:3306/wh_pay_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
            username: root
            password: zxhz@#_123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
        smz:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.1.103:3306/wh_smz_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
            username: root
            password: zxhz@#_123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
        oracle:
            driver-class-name: oracle.jdbc.driver.OracleDriver
            url: jdbc:oracle:thin:@//192.168.1.103:1521/orcl
            username: MUTUAL_WEIHAI
            password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            #Oracle需要打开注释
            validation-query: SELECT 1 FROM DUAL

##mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zxhz.*.entity
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: warning
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"未设置主键类型",2:"用户输入ID (该类型可以通过自己注册自动填充插件进行填充)", 3:"全局唯一ID (idWorker), 4:全局唯一ID (UUID), 5:字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: UUID
      #字段验证策略 IGNORED:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", DEFAULT 默认的,一般只用于注解里(1. 在全局里代表 NOT_NULL,2. 在注解里代表 跟随全局)
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除值
      logic-delete-value: 0
      #逻辑未删除值
      logic-not-delete-value: 1
knife4j:
  enable: true
  basic:
    enable: false
    username: zxhz
    password: zxhz123456